### PR TITLE
Rename MultiSet::freq() -> MultiSet::frequencyOf()

### PR DESCRIPTION
**Pull request by Majkl578**
In order to avoid abbreviation.

### CODE REVIEW

**Comment by rtheunissen** [comment]
I don't have a problem with `freq` - the abbreviation is not ambiguous. What if we allowed a parameter to `count`? ie `$mset->count($x);`?

**Comment by Majkl578** [comment]
That won't be compatible with Countable, and making it optional would be weird. :|

**Comment by rtheunissen** [comment]
Countable on Multiset is a bit weird anyway.. is it the number of keys or sum of all frequencies? Could consider having Multiset not implement Countable.

**Comment by rtheunissen** [comment]
C++ uses `count`: 
http://www.cplusplus.com/reference/set/multiset/count/

Guava uses `count`: https://google.github.io/guava/releases/21.0/api/docs/com/google/common/collect/Multiset.html#count-java.lang.Object-

Java uses `Collections.frequency`:
https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html?is-external=true#frequency-java.util.Collection-java.lang.Object-

Python's `Counter` does not provide a method (array access only):
https://docs.python.org/2/library/collections.html#collections.Counter

Rust uses `count_of`:
https://docs.rs/multiset/0.0.5/multiset/struct.HashMultiSet.html#method.count_of

---

The Rust example is interesting because it has `MultiSet` as an interface and `HashMultiSet` and an implementation. We are currently proposing a `MultiSet` implementation based on the same BST as `TreeSet`, but there is no requirement for a `MultiSet` to be ordered. But I also don't think we should restrict this to hashable objects only (and scalars of course). 

What if we made `MultiSet` an interface that extends `Set`, and we have two implementations: `TreeMultiSet` and `HashMultiSet`. Both already have defined internals so there is very little cost in providing both. 

`TreeMultiSet`:
- Always sorted by key (not count).
- `O(log n)` count access and insert.
- Supports any key.

`HashMultiSet`:
- Insertion order is preserved (based on the same htable as HashMap)
- `O(1)` count access and update.
- Object keys must be hashable.

IMO there is enough of a difference here for both to exist without ambiguity.

**Comment by rtheunissen** [comment]
`countOf` is good, or array access only.

```
// A
$freq = $mset->countOf($a);

// B
$freq = $mset[$a];

// C
$freq = $mset->getCount($a);

// D ( does not implement Countable)
$freq = $mset->count($a); 

// E
$freq = $mset->frequencyOf($a);
```

---

My ranked choice would be:
- D (Consistent and eliminates ambiguity of count = num of keys vs. count = sum of frequencies)
- A (matches naming precedent of `indexOf` which is nice)
- B (short and simple but can't use as a callable)
- C (We don't really have get* methods in the API so far)
- E (too long)

**Comment by enumag** [comment]
`countOf` is good in my opinion. I dislike `freq` because I don't like abbreviations in code (even when they are not ambiguous). The length argument for using abbreviations is obsolete since we have IDE autocompletion.

**Comment by rtheunissen** [comment]
@enumag do you think that it should also be countable, and have `count(): int` behave the same as a `Set` would, ie. number of keys?

**Comment by enumag** [comment]
@rtheunissen Yes, I do. `count` is too widely used for `\Countable` to having the method do something different and requiring a parameter could leave to confusion in my opinion.

One thing to note however is that if we use `count` then `countOf` could actually be considered worse than `frequencyOf`. The common prefix of `count` and `countOf` means that writing `countOf` would actually require more keystrokes than writing `frequencyOf` despite being shorter. By this I simply want to point out that longer name is not necessarily worse choice.

**Comment by rtheunissen** [comment]
> One thing to note however is that if we use `count` then `countOf` could actually be considered worse than `frequencyOf`. The common prefix of `count` and `countOf` means that writing `countOf` would actually require more keystrokes than writing `frequencyOf` despite being shorter. By this I simply want to point out that longer name is not necessarily worse choice.

That is a good point. How about `numberOf`?

**Comment by enumag** [comment]
Fine by me. What do you think @Majkl578?

**Comment by rtheunissen** [comment]
Also thoughts on `MultiSet`, `HashMultiSet`, `TreeMultiSet`?

**Comment by enumag** [comment]
I'm fine with `MultiSet` personally. From the name I need to know what the structure is but I'm not interested in how it is implemented - hashes and tree are internal details I think.

**Comment by rtheunissen** [comment]
```php
/* Hash-based default implementation */
final class MultiSet implements MutableSet {}

/* BST-based implementation, sorted, no hashing. */
final class TreeMultiSet implements MutableSet, SortedSet {}
```

**Comment by rtheunissen** [comment]
This is now `countOf`

**Pull request closed without merging**
